insert into PAIS values (1, 'Argentina');

insert into PROVINCIA values (1, 1, 'Buenos Aires');
insert into PROVINCIA values (2, 1, 'Capital Federal');
insert into PROVINCIA values (3, 1, 'Catamarca');
insert into PROVINCIA values (4, 1, 'Chaco');
insert into PROVINCIA values (5, 1, 'Chubut');
insert into PROVINCIA values (6, 1, 'Cordoba');
insert into PROVINCIA values (7, 1, 'Corrientes');
insert into PROVINCIA values (8, 1, 'Entre Rios');
insert into PROVINCIA values (9, 1, 'Formosa');
insert into PROVINCIA values (10, 1, 'Jujuy');
insert into PROVINCIA values (11, 1, 'La Pampa');
insert into PROVINCIA values (12, 1, 'La Rioja');
insert into PROVINCIA values (13, 1, 'Mendoza');
insert into PROVINCIA values (14, 1, 'Misiones');
insert into PROVINCIA values (15, 1, 'Neuquen');
insert into PROVINCIA values (16, 1, 'Rio Negro');
insert into PROVINCIA values (17, 1, 'Salta');
insert into PROVINCIA values (18, 1, 'San Juan');
insert into PROVINCIA values (19, 1, 'San Luis');
insert into PROVINCIA values (20, 1, 'Santa Cruz'); 